{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "af40fed4-8bee-427e-9085-f79fe6189732",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import requests\n",
    "from streamlit_lottie import st_lottie\n",
    "from PIL import Image\n",
    "\n",
    "def load_lottieurl(url):\n",
    "    r = requests.get(url)\n",
    "    if r.status_code != 200:\n",
    "        return None\n",
    "    return r.json()\n",
    "\n",
    "# Use local CSS\n",
    "def local_css(file_name):\n",
    "    with open(file_name) as f:\n",
    "        st.markdown(f\"<style>{f.read()}</style>\", unsafe_allow_html=True)\n",
    "\n",
    "def app():\n",
    "    # Load CSS\n",
    "    local_css(\"style/style.css\")\n",
    "    \n",
    "    # Load assets\n",
    "    lottie_coding = load_lottieurl(\"https://assets10.lottiefiles.com/packages/lf20_zzytykf2.json\")\n",
    "    img_sphere = Image.open(\"images/sphere.jpg\")\n",
    "    img_phase_separation = Image.open(\"images/phase_separation.jpg\")\n",
    "    img_nano = Image.open(\"images/nano.jpg\")\n",
    "\n",
    "    # Header Section\n",
    "    with st.container():\n",
    "        st.subheader(\"Hi, I am PolyAI :wave:\")\n",
    "        st.title(\"A Researcher from CAS\")\n",
    "        st.write(\"I'm passionate on fusing polymer physics and artificial intelligence technology.\")\n",
    "        st.write(\"[Learn More >](https://space.bilibili.com/76811961)\")\n",
    "\n",
    "    # What I Do Section\n",
    "    with st.container():\n",
    "        st.write(\"---\")\n",
    "        left_column, right_column = st.columns(2)\n",
    "        with left_column:\n",
    "            st.header(\"What I do\")\n",
    "            st.write(\"\"\"\n",
    "                On my Bilibili channel I am creating tutorials for people who:\n",
    "                - are looking for a way to leverage the power of Blender in their scientific research.\n",
    "                - are struggling with data visualization.\n",
    "                - want to learn Data Analysis & Data Science about polymer science and chemistry.\n",
    "\n",
    "                如果有用，请点个关注，O(∩_∩)O.\n",
    "            \"\"\")\n",
    "            st.write(\"[Bilibili Channel >](https://space.bilibili.com/76811961)\")\n",
    "        with right_column:\n",
    "            st_lottie(lottie_coding, height=300, key=\"coding\")\n",
    "\n",
    "    # Blender Tutorials Section\n",
    "    with st.container():\n",
    "        st.write(\"---\")\n",
    "        st.header(\"Blender tutorials\")\n",
    "        st.write(\"##\")\n",
    "        image_column, text_column = st.columns((1, 2))\n",
    "        with image_column:\n",
    "            st.image(img_sphere)\n",
    "        with text_column:\n",
    "            st.subheader(\"The explosion ball\")\n",
    "            st.write(\"Learn how to model a explosion ball! In this tutorial, I'll show you exactly how to do it\")\n",
    "            st.markdown(\"[Watch Video...](https://www.bilibili.com/video/BV1DK411H795)\")\n",
    "    \n",
    "    with st.container():\n",
    "        image_column, text_column = st.columns((1, 2))\n",
    "        with image_column:\n",
    "            st.image(img_phase_separation)\n",
    "        with text_column:\n",
    "            st.subheader(\"Phase Separation\")\n",
    "            st.write(\"Learn how to create a phase separation texture! In this tutorial, I'll show you exactly how to do it.\")\n",
    "            st.markdown(\"[Watch Video...](https://www.bilibili.com/video/BV1TT4y1J72n)\")\n",
    "    \n",
    "    with st.container():\n",
    "        image_column, text_column = st.columns((1, 2))\n",
    "        with image_column:\n",
    "            st.image(img_nano)\n",
    "        with text_column:\n",
    "            st.subheader(\"Nano Sphere\")\n",
    "            st.write(\"Discover how to make a visually appealing Nano Sphere! In this tutorial, I'll show you exactly how to do it.\")\n",
    "            st.markdown(\"[Watch Video...](https://www.bilibili.com/video/BV1yt4y1277N)\")\n",
    "\n",
    "    # Contact Section\n",
    "    with st.container():\n",
    "        st.write(\"---\")\n",
    "        st.header(\"Get In Touch With Me!\")\n",
    "        st.write(\"##\")\n",
    "\n",
    "        contact_form = \"\"\"\n",
    "        <form action=\"https://formsubmit.co/YOUR@MAIL.COM\" method=\"POST\">\n",
    "            <input type=\"hidden\" name=\"_captcha\" value=\"false\">\n",
    "            <input type=\"text\" name=\"name\" placeholder=\"Your name\" required>\n",
    "            <input type=\"email\" name=\"email\" placeholder=\"Your email\" required>\n",
    "            <textarea name=\"message\" placeholder=\"Your message here\" required></textarea>\n",
    "            <button type=\"submit\">Send</button>\n",
    "        </form>\n",
    "        \"\"\"\n",
    "        left_column, right_column = st.columns(2)\n",
    "        with left_column:\n",
    "            st.markdown(contact_form, unsafe_allow_html=True)\n",
    "        with right_column:\n",
    "            st.empty()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
