{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "8ee47205-77ac-44aa-aaea-a0d58ce64199",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st \n",
    "import numpy as np \n",
    "from io import BytesIO\n",
    "import matplotlib.pyplot as plt\n",
    "from sklearn import datasets\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.decomposition import PCA\n",
    "from sklearn.svm import SVC\n",
    "from sklearn.neighbors import KNeighborsClassifier\n",
    "from sklearn.ensemble import RandomForestClassifier\n",
    "from sklearn.metrics import accuracy_score\n",
    "\n",
    "def get_dataset(name):\n",
    "    data = None\n",
    "    if name == 'Iris':\n",
    "        data = datasets.load_iris()\n",
    "    elif name == 'Wine':\n",
    "        data = datasets.load_wine()\n",
    "    else:\n",
    "        data = datasets.load_breast_cancer()\n",
    "    X = data.data\n",
    "    y = data.target\n",
    "    return X, y\n",
    "\n",
    "def add_parameter_ui(clf_name):\n",
    "    params = dict()\n",
    "    if clf_name == 'SVM':\n",
    "        C = st.sidebar.slider('C', 0.01, 10.0)\n",
    "        params['C'] = C\n",
    "    elif clf_name == 'KNN':\n",
    "        K = st.sidebar.slider('K', 1, 15)\n",
    "        params['K'] = K\n",
    "    else:\n",
    "        max_depth = st.sidebar.slider('max_depth', 2, 15)\n",
    "        params['max_depth'] = max_depth\n",
    "        n_estimators = st.sidebar.slider('n_estimators', 1, 100)\n",
    "        params['n_estimators'] = n_estimators\n",
    "    return params\n",
    "\n",
    "def get_classifier(clf_name, params):\n",
    "    clf = None\n",
    "    if clf_name == 'SVM':\n",
    "        clf = SVC(C=params['C'])\n",
    "    elif clf_name == 'KNN':\n",
    "        clf = KNeighborsClassifier(n_neighbors=params['K'])\n",
    "    else:\n",
    "        clf = RandomForestClassifier(n_estimators=params['n_estimators'], \n",
    "            max_depth=params['max_depth'], random_state=1234)\n",
    "    return clf\n",
    "\n",
    "def app():\n",
    "    st.write(\"\"\"\n",
    "            # Classification\n",
    "            \"\"\")\n",
    "\n",
    "    dataset_name = st.sidebar.selectbox(\n",
    "        'Select Dataset',\n",
    "        ('Iris', 'Breast Cancer', 'Wine')\n",
    "    )\n",
    "\n",
    "    st.write(f\"## {dataset_name} Dataset\")\n",
    "\n",
    "    classifier_name = st.sidebar.selectbox(\n",
    "        'Select classifier',\n",
    "        ('KNN', 'SVM', 'Random Forest')\n",
    "    )\n",
    "\n",
    "    # Get dataset\n",
    "    X, y = get_dataset(dataset_name)\n",
    "    st.write('Shape of dataset:', X.shape)\n",
    "    st.write('number of classes:', len(np.unique(y)))\n",
    "\n",
    "    # Hyper parameters\n",
    "    params = add_parameter_ui(classifier_name)\n",
    "\n",
    "    # Model\n",
    "    clf = get_classifier(classifier_name, params)\n",
    "    \n",
    "    # Train model and plot results\n",
    "    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)\n",
    "\n",
    "    clf.fit(X_train, y_train)\n",
    "    y_pred = clf.predict(X_test)\n",
    "\n",
    "    acc = accuracy_score(y_test, y_pred)\n",
    "\n",
    "    st.write(f'Classifier = {classifier_name}')\n",
    "    st.write(f'Accuracy =', acc)\n",
    "\n",
    "    # Plot dataset\n",
    "    pca = PCA(2)\n",
    "    X_projected = pca.fit_transform(X)\n",
    "\n",
    "    x1 = X_projected[:, 0]\n",
    "    x2 = X_projected[:, 1]\n",
    "\n",
    "    fig, ax = plt.subplots(figsize=(8,6))\n",
    "    ax.scatter(x1, x2,\n",
    "            c=y, alpha=0.8,\n",
    "            cmap='viridis')\n",
    "    ax.set_xlabel('PC1')\n",
    "    ax.set_ylabel('PC2')\n",
    "\n",
    "    buf = BytesIO()\n",
    "    fig.savefig(buf, format=\"png\")\n",
    "    st.image(buf)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
